#!/bin/sh

#  The man page says that only the first file must exist, but on RHEL 5
#  there exists a bug so that only existing files may included in the
#  path
for element in /usr/lib/rpm/rpmrc /usr/lib/rpm/redhat/rpmrc /etc/rpmrc ~/.rpmrc `pwd`/rpmrc; do
    if [ -f $element ]; then
        [ -n "$rc_path" ] && rc_path="$rc_path:"
        rc_path="$rc_path$element"
    fi
done

rpmbuild --rcfile $rc_path "$@"
