-include mk/general.mk ../mk/general.mk ../../mk/general.mk ../../../mk/general.mk ../../../../mk/general.mk ../../../../../mk/general.mk ../../../../../../mk/general.mk

SUBDIRS		:= basic castor usecase stress
SUBDIRS_CLEAN	= $(SUBDIRS)
