#!/bin/bash
##  This script is for running the S2 tests as a job from
##  jenkins.  It is here to make the Jekins job trivial.
##  If the job script is anything other that simply
##  invoking this script then this script is broken and
##  should be fixed.

function check_envar() # $1 name of var
{
    val=$(eval echo \$$1)

    if [ -z "$val" ]; then
        echo "Environment variable $1 is missing"
        exit 1
    fi
}


function check_envars()
{
  for var in "$@"; do
      check_envar "$var"
  done
}

function run_s2() # $1 - prefix to test names in report XML files
{
    voms-proxy-info -all

    for suite in avail basic usecase; do
        echo -e "\n== Starting suite: $suite ==\n"
        if [ ! -d "$1${suite}" ]; then
            mkdir "$1${suite}"
        fi
        export S2_LOGS_DIR=${WORKSPACE}/$1${suite}
        xrunner.py -o "${WORKSPACE}" -p "$1" -d /usr/share/s2/testing/scripts/protos/srm/2.2/${suite}
    done
}


which s2

check_envars WORKSPACE SRM_HOST SRM_PORT SRM_PATH NODE_NAME

# SLEEP_SOR is the sleep-time when polling an SRM GetStatusOf...Request
export SLEEP_SOR=1
export S2_SUPRESS_PROGRESS=1

export SRM_ENDPOINT="srm://${SRM_HOST}:${SRM_PORT}/srm/managerv2?SFN=${SRM_PATH}/${NODE_NAME}"
export X509_USER_PROXY="${WORKSPACE}/proxy-cert"

echo
echo  "ENDPOINT ${SRM_ENDPOINT}"
echo
echo
echo  "Running tests with SHA1 certificate"
echo
voms-proxy-init -rfc --voms desy
run_s2

echo
echo
echo  "Running tests with SHA2 certificate"
echo
#
#  Running voms-proxy-init with -rfc and SHA2 certificate doesn't work, resulting in the following
#  error message:
#
#      [tester1@vm-dcache-wn02 ~]$ voms-proxy-init -cert ~/.globus/TheGreatGonzo-cert.pem -key ~/.globus/TheGreatGonzo-key.pem -rfc --voms desy
#      Your identity: /C=DE/ST=Hamburg/O=dCache.ORG/CN=The Great Gonzo
#      Creating temporary proxy ....................................................................... Done
#      Contacting  grid-voms.desy.de:15104 [/C=DE/O=GermanGrid/OU=DESY/CN=host/grid-voms.desy.de] "desy" Done
#      Creating proxy ......................................................................*** stack smashing detected ***: voms-proxy-init terminated
#      Aborted
#
#  The work-around is to switch off the -rfc and test with old-style proxy certificates for SHA-2
#  certificates.
#
voms-proxy-init -cert ~/.globus/TheGreatGonzo-cert.pem -key ~/.globus/TheGreatGonzo-key.pem --voms desy
run_s2 "SHA2-"
